{"name": "test_delete_tenant_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert True is False", "trace": "self = <test_14_delete_tenant_user.TestDeleteUser object at 0x0064CAD0>\n\n    @pytest.mark.flaky(reruns=3)\n    def test_delete_tenant_user(self):\n    \n        login = Login(self.dr)\n        datas = datainfo.get_xls_to_dict(\"user.xlsx\", \"Sheet1\")[0]\n        data1s = datainfo.get_xls_to_dict(\"user.xlsx\", \"authuser\")[0]\n        aupg = authUserPage.AuthUsertPage(self.dr)\n        ta = userAction.UserAction(self.dr)\n        # t_data = datainfo.get_xls_to_dict(\"tenantdata.xlsx\",\"Sheet1\")[0]\n        login.login(datas[\"username\"], datas[\"password\"])\n        # ta.create_tenant_user(data1s[\"tenantname\"],data1s[\"username\"],data1s[\"firstname\"],data1s[\"password\"],data1s[\"repassword\"],data1s[\"email\"])\n        ta.delete_tenant_user(data1s[\"username\"])\n        aupg.open_authuser()\n    \n        aupg.input_select_user(data1s[\"username\"])\n        flag = self.dr.element_exist(\"xpath->//td\")\n>       assert flag is False\nE       assert True is False\n\ntestcase\\test_14_delete_tenant_user.py:35: AssertionError"}, "attachments": [{"name": "log", "source": "cd37e14a-af52-4923-b594-6386aa99dfac-attachment.txt", "type": "text/plain"}], "start": 1572686928773, "stop": 1572686942960, "uuid": "063a30da-ca88-45b5-8f97-06aa3c74667c", "historyId": "b9e3bb7f20f4cd13fb429a642dff2600", "testCaseId": "74364ad2aaa487ed4a1e7c4382278180", "fullName": "testcase.test_14_delete_tenant_user.TestDeleteUser#test_delete_tenant_user", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_14_delete_tenant_user"}, {"name": "subSuite", "value": "TestDeleteUser"}, {"name": "host", "value": "wuzs"}, {"name": "thread", "value": "18804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_14_delete_tenant_user"}]}